// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// PostsCreate implements Posts_create operation.
//
// POST /posts
func (UnimplementedHandler) PostsCreate(ctx context.Context, req *CreatePostRequest) (r *Post, _ error) {
	return r, ht.ErrNotImplemented
}

// PostsDelete implements Posts_delete operation.
//
// DELETE /posts/{id}
func (UnimplementedHandler) PostsDelete(ctx context.Context, params PostsDeleteParams) error {
	return ht.ErrNotImplemented
}

// PostsList implements Posts_list operation.
//
// GET /posts
func (UnimplementedHandler) PostsList(ctx context.Context) (r *PostList, _ error) {
	return r, ht.ErrNotImplemented
}

// PostsRead implements Posts_read operation.
//
// GET /posts/{id}
func (UnimplementedHandler) PostsRead(ctx context.Context, params PostsReadParams) (r *Post, _ error) {
	return r, ht.ErrNotImplemented
}

// PostsUpdate implements Posts_update operation.
//
// PUT /posts/{id}
func (UnimplementedHandler) PostsUpdate(ctx context.Context, req *UpdatePostRequest, params PostsUpdateParams) (r *Post, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
