// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// AuthMe implements Auth_me operation.
	//
	// GET /auth/me
	AuthMe(ctx context.Context) (*User, error)
	// AuthSignin implements Auth_signin operation.
	//
	// POST /auth/signin
	AuthSignin(ctx context.Context, req *SignInRequest) (*AuthResponse, error)
	// AuthSignup implements Auth_signup operation.
	//
	// POST /auth/signup
	AuthSignup(ctx context.Context, req *SignUpRequest) (*AuthResponse, error)
	// CommentsCreate implements Comments_create operation.
	//
	// POST /posts/{postId}/comments
	CommentsCreate(ctx context.Context, req *CreateCommentRequest, params CommentsCreateParams) (*Comment, error)
	// CommentsDelete implements Comments_delete operation.
	//
	// DELETE /posts/{postId}/comments/{id}
	CommentsDelete(ctx context.Context, params CommentsDeleteParams) error
	// CommentsList implements Comments_list operation.
	//
	// GET /posts/{postId}/comments
	CommentsList(ctx context.Context, params CommentsListParams) (*CommentList, error)
	// CommentsRead implements Comments_read operation.
	//
	// GET /posts/{postId}/comments/{id}
	CommentsRead(ctx context.Context, params CommentsReadParams) (*Comment, error)
	// CommentsUpdate implements Comments_update operation.
	//
	// PUT /posts/{postId}/comments/{id}
	CommentsUpdate(ctx context.Context, req *UpdateCommentRequest, params CommentsUpdateParams) (*Comment, error)
	// PostsCreate implements Posts_create operation.
	//
	// POST /posts
	PostsCreate(ctx context.Context, req *CreatePostRequest) (*Post, error)
	// PostsDelete implements Posts_delete operation.
	//
	// DELETE /posts/{id}
	PostsDelete(ctx context.Context, params PostsDeleteParams) error
	// PostsList implements Posts_list operation.
	//
	// GET /posts
	PostsList(ctx context.Context) (*PostList, error)
	// PostsRead implements Posts_read operation.
	//
	// GET /posts/{id}
	PostsRead(ctx context.Context, params PostsReadParams) (*Post, error)
	// PostsUpdate implements Posts_update operation.
	//
	// PUT /posts/{id}
	PostsUpdate(ctx context.Context, req *UpdatePostRequest, params PostsUpdateParams) (*Post, error)
	// NewError creates *ErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
