// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	CommentsCreateOperation OperationName = "CommentsCreate"
	CommentsDeleteOperation OperationName = "CommentsDelete"
	CommentsListOperation   OperationName = "CommentsList"
	CommentsReadOperation   OperationName = "CommentsRead"
	CommentsUpdateOperation OperationName = "CommentsUpdate"
	PostsCreateOperation    OperationName = "PostsCreate"
	PostsDeleteOperation    OperationName = "PostsDelete"
	PostsListOperation      OperationName = "PostsList"
	PostsReadOperation      OperationName = "PostsRead"
	PostsUpdateOperation    OperationName = "PostsUpdate"
)
