// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	PostsCreateOperation OperationName = "PostsCreate"
	PostsDeleteOperation OperationName = "PostsDelete"
	PostsListOperation   OperationName = "PostsList"
	PostsReadOperation   OperationName = "PostsRead"
	PostsUpdateOperation OperationName = "PostsUpdate"
)
