// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"github.com/labstack/echo/v4"
	"github.com/ritarock/bbs-app/adapter/delivery"
	"github.com/ritarock/bbs-app/adapter/repository"
	"github.com/ritarock/bbs-app/usecase"
	"time"
)

// Injectors from injector.go:

func InitApp(timeout time.Duration) (*echo.Echo, error) {
	db := repository.NewDb()
	postRepository := repository.NewPostRepository(db)
	postUsecase := usecase.NewPostUsecase(postRepository, timeout)
	postHandler := delivery.NewPostHandler(postUsecase)
	echoEcho := delivery.NewRouter(postHandler)
	return echoEcho, nil
}
