// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package query

import (
	"context"
	"database/sql"
	"time"
)

const deleteComment = `-- name: DeleteComment :exec
;

DELETE FROM comments
WHERE id = ?
`

func (q *Queries) DeleteComment(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteComment, id)
	return err
}

const deletePost = `-- name: DeletePost :exec
;

DELETE FROM posts
WHERE id = ?
`

func (q *Queries) DeletePost(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePost, id)
	return err
}

const insertComment = `-- name: InsertComment :execresult
;

INSERT INTO comments (
    post_id, body, commented_at
) VALUES (
    ?, ?, ?
)
`

type InsertCommentParams struct {
	PostID      int64
	Body        string
	CommentedAt time.Time
}

func (q *Queries) InsertComment(ctx context.Context, arg InsertCommentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertComment, arg.PostID, arg.Body, arg.CommentedAt)
}

const insertPost = `-- name: InsertPost :execresult
INSERT INTO posts (
    title, content, posted_at
) VALUES (
    ?, ?, ?
)
`

type InsertPostParams struct {
	Title    string
	Content  string
	PostedAt time.Time
}

func (q *Queries) InsertPost(ctx context.Context, arg InsertPostParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertPost, arg.Title, arg.Content, arg.PostedAt)
}

const insertUser = `-- name: InsertUser :execresult
;

INSERT INTO users (
    email, password_hash, created_at
) VALUES (
    ?, ?, ?
)
`

type InsertUserParams struct {
	Email        string
	PasswordHash string
	CreatedAt    time.Time
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertUser, arg.Email, arg.PasswordHash, arg.CreatedAt)
}

const selectComment = `-- name: SelectComment :one
SELECT id, post_id, body, commented_at FROM comments
WHERE id = ?
`

func (q *Queries) SelectComment(ctx context.Context, id int64) (Comment, error) {
	row := q.db.QueryRowContext(ctx, selectComment, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.Body,
		&i.CommentedAt,
	)
	return i, err
}

const selectCommentsByPostId = `-- name: SelectCommentsByPostId :many
;

SELECT id, post_id, body, commented_at FROM comments
WHERE post_id = ?
ORDER BY id
`

func (q *Queries) SelectCommentsByPostId(ctx context.Context, postID int64) ([]Comment, error) {
	rows, err := q.db.QueryContext(ctx, selectCommentsByPostId, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.Body,
			&i.CommentedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectPost = `-- name: SelectPost :one
SELECT id, title, content, posted_at FROM posts
WHERE id = ?
`

func (q *Queries) SelectPost(ctx context.Context, id int64) (Post, error) {
	row := q.db.QueryRowContext(ctx, selectPost, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.PostedAt,
	)
	return i, err
}

const selectPosts = `-- name: SelectPosts :many
;

SELECT id, title, content, posted_at FROM posts
ORDER BY id
`

func (q *Queries) SelectPosts(ctx context.Context) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, selectPosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.PostedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectUserByEmail = `-- name: SelectUserByEmail :one
SELECT id, email, password_hash, created_at FROM users
WHERE email = ?
`

func (q *Queries) SelectUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, selectUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const selectUserByID = `-- name: SelectUserByID :one
;

SELECT id, email, password_hash, created_at FROM users
WHERE id = ?
`

func (q *Queries) SelectUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, selectUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const updateComment = `-- name: UpdateComment :exec
;

UPDATE comments
SET body = ?
WHERE id = ?
`

type UpdateCommentParams struct {
	Body string
	ID   int64
}

func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) error {
	_, err := q.db.ExecContext(ctx, updateComment, arg.Body, arg.ID)
	return err
}

const updatePost = `-- name: UpdatePost :exec
;

UPDATE posts
SET title = ?, content = ?
WHERE id = ?
`

type UpdatePostParams struct {
	Title   string
	Content string
	ID      int64
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) error {
	_, err := q.db.ExecContext(ctx, updatePost, arg.Title, arg.Content, arg.ID)
	return err
}
