// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package query

import (
	"context"
	"database/sql"
	"time"
)

const deletePost = `-- name: DeletePost :exec
;

DELETE FROM posts
WHERE id = ?
`

func (q *Queries) DeletePost(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePost, id)
	return err
}

const insertPost = `-- name: InsertPost :execresult
INSERT INTO posts (
    title, content, posted_at
) VALUES (
    ?, ?, ?
)
`

type InsertPostParams struct {
	Title    string
	Content  string
	PostedAt time.Time
}

func (q *Queries) InsertPost(ctx context.Context, arg InsertPostParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertPost, arg.Title, arg.Content, arg.PostedAt)
}

const selectPost = `-- name: SelectPost :one
SELECT id, title, content, posted_at FROM posts
WHERE id = ?
`

func (q *Queries) SelectPost(ctx context.Context, id int64) (Post, error) {
	row := q.db.QueryRowContext(ctx, selectPost, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.PostedAt,
	)
	return i, err
}

const selectPosts = `-- name: SelectPosts :many
;

SELECT id, title, content, posted_at FROM posts
ORDER BY id
`

func (q *Queries) SelectPosts(ctx context.Context) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, selectPosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.PostedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePost = `-- name: UpdatePost :exec
;

UPDATE posts
SET title = ?, content = ?
WHERE id = ?
`

type UpdatePostParams struct {
	Title   string
	Content string
	ID      int64
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) error {
	_, err := q.db.ExecContext(ctx, updatePost, arg.Title, arg.Content, arg.ID)
	return err
}
