// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/ritarock/bbs-app/ent/comment"
	"github.com/ritarock/bbs-app/ent/post"
	"github.com/ritarock/bbs-app/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	commentFields := schema.Comment{}.Fields()
	_ = commentFields
	// commentDescCommentedAt is the schema descriptor for commented_at field.
	commentDescCommentedAt := commentFields[1].Descriptor()
	// comment.DefaultCommentedAt holds the default value on creation for the commented_at field.
	comment.DefaultCommentedAt = commentDescCommentedAt.Default.(time.Time)
	postFields := schema.Post{}.Fields()
	_ = postFields
	// postDescPostedAt is the schema descriptor for posted_at field.
	postDescPostedAt := postFields[2].Descriptor()
	// post.DefaultPostedAt holds the default value on creation for the posted_at field.
	post.DefaultPostedAt = postDescPostedAt.Default.(time.Time)
}
